# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Configuración para web1
  config.vm.define "web1" do |web1|
    web1.vm.box = "ubuntu/focal64"  # Box base de Ubuntu 20.04
    web1.vm.network "private_network", ip: "192.168.33.10"  # Dirección IP privada
    web1.vm.hostname = "web1"  # Nombre del host
    web1.vm.provider "virtualbox" do |vb|
      vb.memory = "512"  # Asignar 512MB de memoria RAM
    end

    # Provisión de Apache y configuración de carpeta compartida
    web1.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y apache2
      sudo systemctl enable apache2
      sudo ln -sf /vagrant/index.html /var/www/html/index.html
    SHELL
  end

  # Configuración para web2
  config.vm.define "web2" do |web2|
    web2.vm.box = "ubuntu/focal64"
    web2.vm.network "private_network", ip: "192.168.33.11"
    web2.vm.hostname = "web2"
    web2.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end

    # Provisión de Apache y configuración de carpeta compartida
    web2.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y apache2
      sudo systemctl enable apache2
      sudo ln -sf /vagrant/index.html /var/www/html/index.html
    SHELL
  end

  # Configuración de la carpeta compartida global
  config.vm.synced_folder ".", "/vagrant"

end
